[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x56aed6"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xebf4ff"
yellow = "0xff9e64"

[colors.normal]
black = "0x0A0908"
blue = "0x429eff"
cyan = "0x69e1ff"
green = "0x94e06e"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0xEAE0D5"
yellow = "0xe0af68"

[colors.primary]
background = "0x000000"
foreground = "0xa9b1d6"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.italic]
family = "iA Writer Mono S"
style = "Italic"

[font.normal]
family = "iA Writer Mono S"
style = "normal"

[font.offset]
x = 0
y = 3

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"


[scrolling]
history = 5000
multiplier = 3

[shell]
program = "/usr/bin/fish"

[window]
decorations = "None"
dynamic_padding = false

[window.padding]
x = 16
y = 8
