gram = "/usr/bin/fish"
m = "/usr/bin/fish"
"window.opacity" = 1

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x56aed6"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xebf4ff"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x40a2e3"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.Bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "normal"

[font.offset]
x = 0
y = 1

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[schemes.maintheme.bright]
black = "0x141414"
blue = "0x7c6eff"
cyan = "0x309fff"
green = "0x57B262"
magenta = "0xe778ff"
red = "0xF44708"
white = "0xF1F6F9"
yellow = "0xfff457"

[schemes.maintheme.normal]
black = "0x000000"
blue = "0x2b7af0"
cyan = "0x8a77ed"
green = "0x57B262"
magenta = "0xe165fc"
red = "0xF44708"
white = "0xd5c1d9"
yellow = "0xfff23b"

[schemes.maintheme.primary]
background = "0x000000"
foreground = "0xa9b1d6"

[schemes.tokyo-night.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x56aed6"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xebf4ff"
yellow = "0xff9e64"

[schemes.tokyo-night.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x40a2e3"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[schemes.tokyo-night.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[schemes.tokyo-night-storm.bright]
black = "0x2d4373"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night-storm.normal]
black = "0x213154"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[schemes.tokyo-night-storm.primary]
background = "0x24283b"
foreground = "0xa9b1d6"

[scrolling]
history = 5000
multiplier = 3

[shell]
program = "/usr/bin/fish"

[window]
decorations = "None"
dynamic_padding = false

[window.padding]
x = 16
y = 8
